apiVersion: v1
kind: Pod
metadata:
  name: nginx-blocked
spec:
  nodeSelector:
   kubernetes.io/hostname: monitoring-cluster-worker2
  containers:
    - name: nginx
      image: nginx
---      
apiVersion: v1
kind: Pod
metadata:
  name: nginx-tolerated
spec:
  tolerations:
    - key: "dedicated"
      operator: "Equal"
      value: "database"
      effect: "NoSchedule"
  containers:
    - name: nginx
      image: nginx