apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: nginx-app
  name: argo-manual-ui-app 
rules:
  - apiGroups: [""]
    resources: ["pods", "services"]
    verbs: ["get", "list", "watch", "create", "delete"]